$file = "src\components\guru\GuruHome.jsx"
$lines = Get-Content $file -Encoding UTF8

# Keep lines 1-617 (index 0-616), replace the rest
$keep = $lines[0..616]

$newLines = @(
'  return (',
'    <div className="space-y-4">',
'      {/* Welcome Card */}',
'      <div className="bg-white rounded-2xl shadow-sm border border-gray-100 p-4 relative overflow-hidden">',
'        <div className="absolute left-0 top-0 bottom-0 w-1 bg-indigo-500 rounded-l-2xl" />',
'        <div className="flex items-center gap-3 pl-2">',
'          <div className="w-12 h-12 bg-indigo-50 rounded-xl flex items-center justify-center shrink-0">',
'            <span className="text-xl font-black text-indigo-500">',
"              {(user?.nama || '').charAt(0)?.toUpperCase() || '\ud83d\udc4b'}",
'            </span>',
'          </div>',
'          <div className="flex-1 min-w-0">',
'            <p className="text-xs text-slate-400 font-semibold uppercase tracking-widest">Selamat Datang</p>',
'            <h2 className="text-base font-bold text-slate-800 leading-tight truncate">',
"              {user?.nama || 'Guru'}",
'            </h2>',
'            <p className="text-xs text-slate-500 mt-0.5">{formatFullDate(new Date())}</p>',
'          </div>',
'        </div>',
'        <div className="flex flex-wrap gap-2 mt-3 pl-2">',
'          <span className="px-2.5 py-1 bg-slate-50 border border-slate-200 rounded-full text-xs text-slate-600 font-medium">',
'            {`\u23f0 Masuk ${settings.jam_masuk_normal} WIB`}',
'          </span>',
'          <span className="px-2.5 py-1 bg-slate-50 border border-slate-200 rounded-full text-xs text-slate-600 font-medium">',
"            {`\u26a1 Toleransi ${settings.toleransi_terlambat} mnt`}",
'          </span>',
"          {settings.mode_testing == '1' && (",
'            <span className="px-2.5 py-1 bg-orange-50 border border-orange-200 rounded-full text-xs text-orange-600 font-medium">',
'              {`\ud83e\uddea Mode Testing`}',
'            </span>',
'          )}',
'          {isPiketToday && jadwalPiketHariIni && (',
'            <span className="px-2.5 py-1 bg-purple-50 border border-purple-200 rounded-full text-xs text-purple-600 font-medium">',
'              {`\ud83d\udccb Piket \u2014 Maks ${jadwalPiketHariIni.jam_piket} WIB`}',
'            </span>',
'          )}',
'        </div>',
'      </div>',
'',
'      {/* Holiday Message */}',
'      {isHoliday && holidayInfo && (',
'        <div className="bg-white rounded-2xl shadow-sm border border-gray-100 p-5 relative overflow-hidden text-center">',
"          <div className={`absolute left-0 top-0 bottom-0 w-1 rounded-l-2xl \${holidayInfo.type === 'weekend' ? 'bg-indigo-400' : 'bg-violet-400'}`} />",
"          <div className='text-3xl mb-2'>{holidayInfo.type === 'weekend' ? '\ud83d\ude34' : '\ud83c\udf89'}</div>",
'          <h3 className="text-base font-bold text-slate-800">{holidayInfo.message}</h3>',
"          <p className='text-xs text-slate-500 mt-1'>Tidak perlu melakukan presensi hari ini</p>",
'        </div>',
'      )}',
'',
'      {/* Status Display */}',
'      {todayAttendance && !isHoliday ? (',
'        <div className="space-y-3">',
'          {(() => {',
'            const status = todayAttendance.status',
"            const isIzinSakit = status === 'izin' || status === 'sakit'",
"            const isHadirTerlambat = status === 'hadir_terlambat'",
"            const isIzinTerlambat = status === 'hadir_izin_terlambat'",
'            let accentColor, dotColor, badgeBg, badgeText, badgeLabel, headerText',
"            if (status === 'izin') {",
"              accentColor = 'bg-amber-400'; dotColor = 'bg-amber-400'",
"              badgeBg = 'bg-amber-50'; badgeText = 'text-amber-700'",
"              badgeLabel = 'IZIN'; headerText = 'Anda Izin Hari Ini'",
"            } else if (status === 'sakit') {",
"              accentColor = 'bg-rose-400'; dotColor = 'bg-rose-400'",
"              badgeBg = 'bg-rose-50'; badgeText = 'text-rose-700'",
"              badgeLabel = 'SAKIT'; headerText = 'Anda Sakit Hari Ini'",
'            } else if (isHadirTerlambat) {',
"              accentColor = 'bg-amber-400'; dotColor = 'bg-amber-400'",
"              badgeBg = 'bg-yellow-50'; badgeText = 'text-yellow-700'",
"              badgeLabel = 'TERLAMBAT'; headerText = 'Anda Sudah Absen'",
'            } else if (isIzinTerlambat) {',
"              accentColor = 'bg-blue-400'; dotColor = 'bg-blue-400'",
"              badgeBg = 'bg-blue-50'; badgeText = 'text-blue-700'",
"              badgeLabel = 'IZIN TERLAMBAT'; headerText = 'Anda Sudah Absen'",
'            } else {',
"              accentColor = 'bg-emerald-400'; dotColor = 'bg-emerald-400'",
"              badgeBg = 'bg-emerald-50'; badgeText = 'text-emerald-700'",
"              badgeLabel = 'HADIR'; headerText = 'Anda Sudah Absen'",
'            }',
'            return (',
'              <>',
'                <div className="bg-white rounded-2xl shadow-sm border border-gray-100 p-4 relative overflow-hidden">',
'                  <div className={`absolute left-0 top-0 bottom-0 w-1 rounded-l-2xl ${accentColor}`} />',
'                  <div className="pl-2">',
'                    <div className="flex items-center justify-between mb-3">',
'                      <div className="flex items-center gap-2">',
'                        <div className={`w-2.5 h-2.5 rounded-full ${dotColor}`} />',
'                        <span className="text-sm font-bold text-slate-800">{headerText}</span>',
'                      </div>',
'                      <span className={`px-2.5 py-0.5 rounded-full text-xs font-bold ${badgeBg} ${badgeText}`}>',
'                        {badgeLabel}',
'                      </span>',
'                    </div>',
'                    <div className="space-y-0">',
'                      {todayAttendance.jamHadir && (',
'                        <div className="flex justify-between items-center py-2 border-b border-slate-50">',
'                          <span className="text-xs text-slate-400 font-medium">Jam Masuk</span>',
'                          <span className="text-xs font-semibold text-slate-700">{todayAttendance.jamHadir}</span>',
'                        </div>',
'                      )}',
'                      {todayAttendance.jamIzin && (',
'                        <div className="flex justify-between items-center py-2 border-b border-slate-50">',
'                          <span className="text-xs text-slate-400 font-medium">Jam Izin</span>',
'                          <span className="text-xs font-semibold text-slate-700">{todayAttendance.jamIzin}</span>',
'                        </div>',
'                      )}',
'                      {todayAttendance.jamSakit && (',
'                        <div className="flex justify-between items-center py-2 border-b border-slate-50">',
'                          <span className="text-xs text-slate-400 font-medium">Jam Sakit</span>',
'                          <span className="text-xs font-semibold text-slate-700">{todayAttendance.jamSakit}</span>',
'                        </div>',
'                      )}',
'                      {isHadirTerlambat && todayAttendance.keterangan && (',
'                        <div className="flex justify-between items-center py-2 border-b border-slate-50">',
'                          <span className="text-xs text-slate-400 font-medium">Terlambat</span>',
'                          <span className="text-xs font-semibold text-amber-600">{todayAttendance.keterangan}</span>',
'                        </div>',
'                      )}',
'                      <div className="flex justify-between items-center py-2">',
'                        <span className="text-xs text-slate-400 font-medium">Jam Pulang</span>',
'                        <span className={`text-xs font-semibold ${(todayAttendance.jamPulang || todayAttendance.jam_pulang) ? "text-slate-700" : "text-slate-300"}`}>',
"                          {todayAttendance.jamPulang || todayAttendance.jam_pulang || 'Belum tercatat'}",
'                        </span>',
'                      </div>',
'                      {todayAttendance.keterangan && !isHadirTerlambat && (',
'                        <div className="flex justify-between items-center py-2 border-t border-slate-50">',
'                          <span className="text-xs text-slate-400 font-medium">Keterangan</span>',
'                          <span className="text-xs font-medium text-slate-600 text-right max-w-xs">{todayAttendance.keterangan}</span>',
'                        </div>',
'                      )}',
'                    </div>',
'                    {isIzinSakit && (',
'                      <div className="mt-3 px-3 py-2 bg-slate-50 rounded-xl">',
'                        <p className="text-xs text-slate-500">',
"                          {`\u2139\ufe0f Tidak perlu presensi pulang untuk status \${status === 'izin' ? 'izin' : 'sakit'}.`}",
'                        </p>',
'                      </div>',
'                    )}',
'                  </div>',
'                </div>',
'',
"                {!isIzinSakit && settings.button_enabled == '1' && (status === 'hadir' || isHadirTerlambat || isIzinTerlambat) && !todayAttendance.jamPulang && !todayAttendance.jam_pulang && (",
'                  <>',
'                    {canShowPulangButton() ? (',
'                      <button',
'                        onClick={handlePulang}',
'                        disabled={loading}',
'                        className="w-full bg-indigo-600 text-white py-4 rounded-2xl font-bold text-base hover:bg-indigo-700 disabled:bg-slate-300 disabled:text-slate-500 flex items-center justify-center gap-3 shadow-sm transition-all"',
'                      >',
'                        <CheckCircle className="w-5 h-5" />',
"                        {loading ? 'Memproses...' : 'PRESENSI PULANG'}",
'                      </button>',
'                    ) : (',
'                      <div className="bg-slate-50 border border-slate-200 rounded-2xl p-4 text-center">',
"                        <p className='text-slate-600 font-semibold text-sm'>\u23f0 Presensi pulang tersedia mulai 09:00 WIB</p>",
"                        <p className='text-xs text-slate-400 mt-1'>Silakan tunggu hingga jam 09:00</p>",
'                      </div>',
'                    )}',
'                  </>',
'                )}',
'',
"                {!isIzinSakit && (status === 'hadir' || isHadirTerlambat || isIzinTerlambat) && (todayAttendance.jamPulang || todayAttendance.jam_pulang) && (",
'                  <div className="bg-emerald-50 border border-emerald-200 rounded-2xl p-3.5 text-center">',
'                    <p className="text-emerald-700 font-semibold text-sm">\u2713 Presensi pulang sudah tercatat</p>',
'                  </div>',
'                )}',
'              </>',
'            )',
'          })()}',
'        </div>',
'      ) : null}',
'',
'      {/* Action Buttons */}',
'      {(() => {',
'        const sudahPulang = todayAttendance && (todayAttendance.jam_pulang || todayAttendance.jamPulang)',
"        const isIzinSakit = todayAttendance && (todayAttendance.status === 'izin' || todayAttendance.status === 'sakit')",
'        if (isHoliday || sudahPulang || isIzinSakit) return null',
'        return (',
'        <div className="space-y-3 mb-6">',
'          <button',
'            onClick={() => setShowQRScanner(true)}',
'            disabled={loading}',
'            className={`w-full py-4 rounded-2xl font-bold text-base flex items-center justify-center gap-3 shadow-sm transition-all hover:opacity-90 active:scale-[0.99] disabled:bg-slate-300 disabled:text-slate-500 ${',
"              !todayAttendance ? 'bg-indigo-600 text-white' : 'bg-violet-600 text-white'",
'            }`}',
'          >',
'            <QrCode className="w-6 h-6" />',
"            <span>{!todayAttendance ? 'SCAN PRESENSI MASUK' : settings.qr_enabled == '1' ? 'SCAN PRESENSI PULANG' : 'PRESENSI PULANG'}</span>",
'          </button>',
'',
"          {settings.button_enabled == '1' && (",
'            <>',
'              <div className="flex items-center gap-3">',
'                <div className="flex-1 h-px bg-slate-200" />',
'                <span className="text-slate-400 text-xs font-medium">atau presensi manual</span>',
'                <div className="flex-1 h-px bg-slate-200" />',
'              </div>',
'              <button',
'                onClick={handleHadir}',
'                disabled={loading}',
'                className="w-full bg-emerald-500 text-white py-4 rounded-2xl font-bold text-base hover:bg-emerald-600 disabled:bg-slate-300 disabled:text-slate-500 flex items-center justify-center gap-3 shadow-sm transition-all"',
'              >',
'                <CheckCircle className="w-5 h-5" />',
"                {loading ? 'Memproses...' : 'HADIR'}",
'              </button>',
'            </>',
'          )}',
'',
'          <div className="grid grid-cols-2 gap-3">',
'            <button',
"              onClick={() => handleIzinSakit('izin')}",
'              disabled={loading}',
'              className="bg-amber-400 text-white py-4 rounded-2xl font-bold text-base hover:bg-amber-500 disabled:bg-slate-300 disabled:text-slate-500 flex items-center justify-center gap-2 shadow-sm transition-all"',
'            >',
'              <FileText className="w-5 h-5" />',
'              IZIN',
'            </button>',
'            <button',
"              onClick={() => handleIzinSakit('sakit')}",
'              disabled={loading}',
'              className="bg-rose-400 text-white py-4 rounded-2xl font-bold text-base hover:bg-rose-500 disabled:bg-slate-300 disabled:text-slate-500 flex items-center justify-center gap-2 shadow-sm transition-all"',
'            >',
'              <AlertCircle className="w-5 h-5" />',
'              SAKIT',
'            </button>',
'          </div>',
'        </div>',
'        )',
'      })()}',
'',
'      {/* QR Scanner Modal */}',
'      {showQRScanner && (',
'        <QRScanner',
'          user={user}',
'          settings={settings}',
'          attendanceStatus={{',
'            has_checked_in: !!todayAttendance,',
"            has_checked_out: !!(todayAttendance?.jam_pulang || todayAttendance?.jamPulang)",
'          }}',
'          onClose={() => setShowQRScanner(false)}',
'          onSuccess={() => {',
'            setShowQRScanner(false)',
"            setMessage({ type: 'success', text: '\u2705 Presensi berhasil dicatat!' })",
'            checkTodayAttendance()',
'            setTimeout(() => setMessage({ type: "", text: "" }), 4000)',
'          }}',
'        />',
'      )}',
'',
'      {/* Message */}',
'      {message.text && (',
'        <div className={`p-4 rounded-2xl whitespace-pre-line text-sm font-medium ${',
"          message.type === 'success' ? 'bg-emerald-50 text-emerald-700 border border-emerald-200' :",
"          message.type === 'warning' ? 'bg-amber-50 text-amber-700 border border-amber-200' :",
"          'bg-rose-50 text-rose-700 border border-rose-200'",
'        }`}>',
'          {message.text}',
'        </div>',
'      )}',
'',
'      {/* Modal Izin/Sakit */}',
'      {showModal && (',
'        <div className="fixed inset-0 bg-black/50 backdrop-blur-sm flex items-end sm:items-center justify-center p-4 z-50">',
'          <div className="bg-white rounded-2xl w-full max-w-md p-6 shadow-2xl">',
'            <h3 className="text-base font-bold text-slate-800 mb-1">',
"              {`Keterangan \${modalType === 'izin' ? 'Izin' : 'Sakit'}`}",
'            </h3>',
"            <p className='text-xs text-slate-400 mb-4'>{`Masukkan alasan \${modalType === 'izin' ? 'izin' : 'sakit'} Anda`}</p>",
'            <textarea',
'              value={keterangan}',
'              onChange={(e) => setKeterangan(e.target.value)}',
'              className="w-full px-4 py-3 border border-slate-200 rounded-xl focus:ring-2 focus:ring-indigo-500 focus:border-transparent text-sm text-slate-700 placeholder:text-slate-300 mb-4 resize-none"',
'              rows="3"',
'              placeholder="Contoh: Keperluan keluarga mendesak..."',
'            />',
'            <div className="flex gap-3">',
'              <button',
'                onClick={() => setShowModal(false)}',
'                className="flex-1 px-4 py-3 border border-slate-200 text-slate-600 rounded-xl hover:bg-slate-50 font-semibold text-sm transition-colors"',
'              >',
'                Batal',
'              </button>',
'              <button',
'                onClick={submitIzinSakit}',
'                className="flex-1 px-4 py-3 bg-indigo-600 text-white rounded-xl hover:bg-indigo-700 font-semibold text-sm transition-colors"',
'              >',
'                Simpan',
'              </button>',
'            </div>',
'          </div>',
'        </div>',
'      )}',
'    </div>',
'  )',
'}',
'',
'export default GuruHome'
)

$combined = $keep + $newLines
Set-Content -Path $file -Value $combined -Encoding UTF8
Write-Host "DONE. Total lines: $($combined.Length)"
